### ISSUE TITLE
Utilize NLP

### ISSUE THREAD

**Issue by carlthome** [ai14/prosammgen#2]
Implement a NLP to guarantee that the output is grammar correct. It's possible that given enough training data a NLP won't be necessary, but it will always be a good extra precaution. Hard part: getting the NLP logic into the text generation flow.

**Comment by nandezer** [comment]
For the NLP I found the code of NLP from Stanford, which is s they say in their web site "The Stanford CoreNLP code is written in Java and licensed under the GNU General Public License"

http://nlp.stanford.edu/software/corenlp.shtml#About

I will look into it and download and see what is exactly, this is only a update on how it goes.

**Comment by nandezer** [comment]
There is also a library from Java already did it for that, it's call:  the OpenNLP CCG Library
the link is this one: http://opennlp.apache.org/index.html

**Comment by carlthome** [comment]
If we want to use some basic NLP stuff it's available in the Synonyms class.
