### ISSUE TITLE
Identify seminar question keywords and reuse them in the answers when generating the reflection document

### ISSUE THREAD

**Issue by carlthome** [ai14/prosammgen#4]

**Comment by carlthome** [comment]
I'm leaving this to you @dflemstr. We need an implementation before Monday midday.

There are several scientific ways of generating keywords from texts (i.e. extracting the most interesting words and phrases from a given text) and we need this in prosammgen because the grammar wants to repeat the each seminar question's keyword in the same question's answer. This will hopefully improve the likelihood of fooling people into thinking the reflection document was typed by a human.

More importantly, this addition of keyword identification will give our report scientific weight.

Implement the interface KeywordIdentifier and make sure to document which algorithms you use and why. Then, when writing the report, you'll mostly focus on writing about finding keywords in texts, almost as a sub-report in the bigger picture of prosammgen.

Some quick googling got the following:

https://stackoverflow.com/questions/4882486/how-to-identify-tags-key-words-automatically-from-a-given-text
https://stackoverflow.com/questions/2661778/tag-generation-from-a-text-content
https://en.wikipedia.org/wiki/Tf%E2%80%93idf
https://stackoverflow.com/questions/2452982/how-to-extract-common-significant-phrases-from-a-series-of-text-entries

**Comment by dflemstr** [comment]
There are too few words to use TF-IDF, so a pragmatic stopwords solution is my first direction of attack.

**Comment by carlthome** [comment]
Done?

**Comment by dflemstr** [comment]
I think so, yes. We are now using full NLP tagging, so we can't really do better with the limited info we have.
