### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by carlthome** [ai14/prosammgen#8]

**Comment by dflemstr** [comment]
Why should we have a web interface?

**Comment by carlthome** [comment]
Note the milestone. It's not relevant to the project report or the AI course, but just an extra feature I'd like to add on my own time.

**Comment by carlthome** [comment]
Closing because project is done.

**Comment by carlthome** [comment]
Also web interface was great fun while it lasted, @dflemstr. 🙃
