### ISSUE TITLE
Design a grammar

### ISSUE THREAD

**Issue by carlthome** [ai14/prosammgen#9]

**Comment by carlthome** [comment]
@nandezer Could you provide your thoughts on how to design a grammar from a scientific point of view? We need to know that what we are designing is actually relevant to something more substantial than our intuition. Why should a grammar look the way it looks for optimally generating text, for example?

**Comment by carlthome** [comment]
@johnPertoft @dflemstr @nandezer Everyone is expected to go into res/grammar and contribute some smart stuff that improves the text generation. The longer the better, really. The file starts with a short readme on the format. Feel free to ask @johnPertoft (or me) questions if you're uncertain.

**Comment by dflemstr** [comment]
I needed to support back-references within productions (so that I don't have to type out the grammar as a DAG). I will quickly refactor the grammar parser to support this.

**Comment by carlthome** [comment]
:+1:

**Comment by carlthome** [comment]
Issue basically done. Grammar could be expanded upon though.
